services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.8
    container_name: clickhouse
    restart: unless-stopped
    environment:
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    ports:
      - "14123:8123" # Interface HTTP / Web
      - "14200:9000" # Cliente nativo / TCP
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./data:/var/lib/clickhouse
      - ./backups:/backups
      - ./logs:/var/log/clickhouse-server
      - ./clickhouse/config.xml:/etc/clickhouse-server/config.d/listen.xml:ro
    networks:
      - clickhouse-network

networks:
  clickhouse-network:
    name: clickhouse-network
